"""Regenerate the whole synthetic world.

    uv run python -m generation.run --n 5250 --seed 2026        # full volume
    uv run python -m generation.run --n 200                     # sample with the 8 heroes

Writes data/raw/*.csv, data/graphe/*.csv and data/raw/README.md, then runs generation.checks.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

from . import config as cfg
from .activite import World, finalise_margin_compression, inject_scenarios, simulate_activity
from .adeb import simulate_adeb
from .controles import build_ground_truth, simulate_controls
from .declarations import simulate_declarations
from .douane import bind_nomenclature, simulate_customs
from .employeur import simulate_employer
from .graphe import build_edges, build_metrics
from .population import CONTRIBUABLES_COLUMNS, build_population
from .referentiels import build_ref_tables

RAW_TABLES = [
    "contribuables", "declarations_mensuelles", "declarations_is", "employeur_annexe1_synthese", "employeur_annexe2",
    "employeur_annexe5", "douane_declarations", "douane_articles", "douane_liquidation", "fournisseurs_etrangers",
    "adeb_paiements", "historique_controles", "verite_terrain",
    "ref_nat", "ref_gouvernorats", "ref_ndp", "ref_codes", "ref_taux_retenue", "ref_acheteurs_publics",
]
PRECISION = {"taux_change": 5, "part_achats_coquilles": 4, "poids_entreprises": 4}


def to_csv(df: pd.DataFrame, path: Path) -> None:
    df = df.copy()
    for c in df.columns:
        s = df[c]
        if pd.api.types.is_datetime64_any_dtype(s):
            df[c] = s.dt.strftime("%Y-%m-%d").fillna("")
        elif pd.api.types.is_bool_dtype(s):
            df[c] = np.where(s, "true", "false")
        elif pd.api.types.is_float_dtype(s):
            df[c] = s.round(PRECISION.get(c, 3))
    df.to_csv(path, index=False, encoding="utf-8")


def _stage(name: str, t0: list[float]) -> None:
    now = time.perf_counter()
    print(f"  {name:<34s} {now - t0[0]:6.1f} s", flush=True)
    t0[0] = now


def generate(n: int = cfg.N_DEFAULT, seed: int = cfg.SEED, out: Path = Path("data")) -> World:
    seeds = np.random.SeedSequence(seed).spawn(12)
    rng = lambda k: np.random.default_rng(seeds[k])  # noqa: E731  one independent stream per stage
    clock = [time.perf_counter()]
    start = clock[0]
    print(f"Basira generation: n={n} seed={seed} -> {out}/")

    ref = build_ref_tables()
    bind_nomenclature(ref["ref_ndp"])
    comp = build_population(n, rng(0))
    w = World(comp=comp, rng=rng(1), ref=ref)
    _stage("population", clock)
    simulate_activity(w)
    w.rng = rng(2)
    inject_scenarios(w)
    _stage("activity and scenarios", clock)
    w.rng = rng(3)
    simulate_customs(w)
    finalise_margin_compression(w)
    _stage("customs (SINDA)", clock)
    w.rng = rng(4)
    simulate_adeb(w)
    _stage("public payments (ADEB)", clock)
    w.rng = rng(5)
    simulate_employer(w)
    _stage("employer annexes I, II, V", clock)
    w.rng = rng(6)
    simulate_declarations(w)
    _stage("monthly and IS declarations", clock)
    w.rng = rng(7)
    simulate_controls(w)
    build_ground_truth(w)
    _stage("controls and ground truth", clock)

    contrib = comp[CONTRIBUABLES_COLUMNS].copy()
    w.tables["contribuables"] = contrib.sort_values("mf").reset_index(drop=True)
    for k, v in ref.items():
        w.tables[k] = v[[c for c in v.columns if not c.startswith("_")]]

    w.graphe["aretes"] = build_edges(w.tables)
    w.graphe["metriques_noeuds"] = build_metrics(w.tables, comp)
    _stage("graph", clock)

    raw, gdir = out / "raw", out / "graphe"
    raw.mkdir(parents=True, exist_ok=True)
    gdir.mkdir(parents=True, exist_ok=True)
    for name in RAW_TABLES:
        to_csv(w.tables[name], raw / f"{name}.csv")
    for name, df in w.graphe.items():
        to_csv(df, gdir / f"{name}.csv")
    write_readme(w, raw, n, seed)
    _stage("write CSV", clock)
    print(f"  total {time.perf_counter() - start:.1f} s")
    return w


def write_readme(w: World, raw: Path, n: int, seed: int) -> None:
    lines = [
        "# data/raw - synthetic Basira world",
        "",
        f"Generated by `uv run python -m generation.run --n {n} --seed {seed}`. All data is synthetic;",
        "the shapes follow modele_donnees.md Part 2. `verite_terrain.csv` is the hidden ground truth and must only",
        "be read by the evaluation (never by signals or training).",
        "",
        f"- Seed: {seed}",
        f"- Companies: {n}",
        f"- Activity window: {cfg.WINDOW_START} to {cfg.WINDOW_END}; extraction date {cfg.SNAPSHOT_DATE.date()}",
        "",
        "| Table | Rows | Columns |",
        "|---|---:|---:|",
    ]
    for name in RAW_TABLES:
        df = w.tables[name]
        lines.append(f"| `{name}.csv` | {len(df):,} | {df.shape[1]} |")
    for name, df in w.graphe.items():
        lines.append(f"| `../graphe/{name}.csv` | {len(df):,} | {df.shape[1]} |")
    lines += ["", "Scenario counts (from the ground truth):", "", "| Scenario | Companies |", "|---|---:|"]
    for scen, cnt in w.tables["verite_terrain"]["scenario"].value_counts().sort_index().items():
        lines.append(f"| {scen} | {cnt} |")
    (raw / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Generate the Basira synthetic data (member A).")
    ap.add_argument("--n", type=int, default=cfg.N_DEFAULT, help="number of companies (default 5250; 200 for the sample)")
    ap.add_argument("--seed", type=int, default=cfg.SEED)
    ap.add_argument("--out", type=Path, default=Path("data"), help="output root (raw/ and graphe/ are created inside)")
    ap.add_argument("--skip-checks", action="store_true")
    args = ap.parse_args(argv)
    generate(args.n, args.seed, args.out)
    if args.skip_checks:
        return 0
    from .checks import run_checks

    return 0 if run_checks(args.out) else 1


if __name__ == "__main__":
    sys.exit(main())
